name: transformer_env
channels: 
  - defaults
dependencies:
  - python=3.9
  - pip
  - pip:
    - pip-tools
    - torch
    - datasets
    - numpy<2.0.0
    - tiktoken
    - python-dotenv
    - wandb
    - omegaconf
    - tokenizers
    - pre-commit
    - black


